/**
 * generated by Xtext
 */
package de.thm.mni.htmlgen.validation;

import de.thm.mni.htmlgen.validation.AbstractHTMLGenValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class HTMLGenValidator extends AbstractHTMLGenValidator {
}
