/*
 * generated by Xtext
 */
package de.thm.mni.htmlgen.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class HTMLGenUiModule extends de.thm.mni.htmlgen.ui.AbstractHTMLGenUiModule {
	public HTMLGenUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
