/*
 * generated by Xtext
 */
package de.thm.mni.hochschule.mydsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends de.thm.mni.hochschule.mydsl.AbstractMyDslRuntimeModule {

}
