/**
 * generated by Xtext
 */
package de.thm.mni.hochschule.mydsl.ui.contentassist;

import de.thm.mni.hochschule.mydsl.ui.contentassist.AbstractMyDslProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class MyDslProposalProvider extends AbstractMyDslProposalProvider {
}
