/*
 * generated by Xtext
 */
package de.thm.mni.htmlgen.ui.contentassist

import de.thm.mni.htmlgen.ui.contentassist.AbstractHTMLGenProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class HTMLGenProposalProvider extends AbstractHTMLGenProposalProvider {
}
