/*
 * generated by Xtext
 */
package de.thm.mni.htmlgen;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class HTMLGenStandaloneSetup extends HTMLGenStandaloneSetupGenerated{

	public static void doSetup() {
		new HTMLGenStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

