/*
 * generated by Xtext
 */
package de.thm.mni.htmlgen;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class HTMLGenRuntimeModule extends de.thm.mni.htmlgen.AbstractHTMLGenRuntimeModule {

}
