/*
 * generated by Xtext
 */
package de.thm.mni.htmlgen;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class HTMLGenUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return de.thm.mni.htmlgen.ui.internal.HTMLGenActivator.getInstance().getInjector("de.thm.mni.htmlgen.HTMLGen");
	}
	
}
