/**
 * generated by Xtext
 */
package htmlgenerator.generator;

import com.google.common.collect.Iterables;
import htmlgenerator.myDsl.Form;
import htmlgenerator.myDsl.Model;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.TreeIterator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.IFileSystemAccess;
import org.eclipse.xtext.generator.IGenerator;
import org.eclipse.xtext.xbase.lib.IteratorExtensions;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class MyDslGenerator implements IGenerator {
  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess fsa) {
    TreeIterator<EObject> _allContents = resource.getAllContents();
    Iterable<EObject> _iterable = IteratorExtensions.<EObject>toIterable(_allContents);
    Iterable<Model> _filter = Iterables.<Model>filter(_iterable, Model.class);
    for (final Model m : _filter) {
      EList<Form> _form = m.getForm();
      for (final Form f : _form) {
        String _name = f.getName();
        String _plus = (_name + ".html");
        CharSequence _compile = this.compile(f);
        fsa.generateFile(_plus, _compile);
      }
    }
  }
  
  public CharSequence compile(final Form form) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("<html>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("<head> <title> ");
    String _name = form.getName();
    _builder.append(_name, "\t");
    _builder.append(" </title> </head>");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("<body>");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("<form action=\"/\" method=\"GET\">");
    _builder.newLine();
    _builder.append("\t\t\t");
    _builder.append("<input type=\"text\" value=\"");
    _builder.append("\" ");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("</form>");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("</body>");
    _builder.newLine();
    _builder.append("</html>");
    _builder.newLine();
    _builder.newLine();
    return _builder;
  }
}
