/*
 * generated by Xtext
 */
package de.thm.mni.hochschule.mydsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MyDslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return de.thm.mni.hochschule.mydsl.ui.internal.MyDslActivator.getInstance().getInjector("de.thm.mni.hochschule.mydsl.MyDsl");
	}
	
}
