/*
 * generated by Xtext
 */
package htmlgenerator.ui.contentassist

import htmlgenerator.ui.contentassist.AbstractMyDslProposalProvider

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class MyDslProposalProvider extends AbstractMyDslProposalProvider {
}
