/*
 * generated by Xtext
 */
package htmlgenerator;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MyDslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return htmlgenerator.ui.internal.MyDslActivator.getInstance().getInjector("htmlgenerator.MyDsl");
	}
	
}
