/*
 * generated by Xtext
 */
package htmlgenerator;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends htmlgenerator.AbstractMyDslRuntimeModule {

}
