/*
 * generated by Xtext
 */
package de.thm.mni.htmlgen.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.thm.mni.htmlgen.services.HTMLGenGrammarAccess;

public class HTMLGenParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private HTMLGenGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.thm.mni.htmlgen.parser.antlr.internal.InternalHTMLGenParser createParser(XtextTokenStream stream) {
		return new de.thm.mni.htmlgen.parser.antlr.internal.InternalHTMLGenParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Model";
	}
	
	public HTMLGenGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(HTMLGenGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
