/*
 * generated by Xtext
 */
package de.thm.mni.htmlgen.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class HTMLGenAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/thm/mni/htmlgen/parser/antlr/internal/InternalHTMLGen.tokens");
	}
}
