/*
 * generated by Xtext
 */
package de.thm.mni.htmlgen.serializer;

import com.google.inject.Inject;
import com.google.inject.Provider;
import de.thm.mni.htmlgen.hTMLGen.Field;
import de.thm.mni.htmlgen.hTMLGen.Form;
import de.thm.mni.htmlgen.hTMLGen.HTMLGenPackage;
import de.thm.mni.htmlgen.hTMLGen.Model;
import de.thm.mni.htmlgen.hTMLGen.MultilineField;
import de.thm.mni.htmlgen.hTMLGen.TextField;
import de.thm.mni.htmlgen.services.HTMLGenGrammarAccess;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.serializer.acceptor.ISemanticSequenceAcceptor;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.diagnostic.ISemanticSequencerDiagnosticProvider;
import org.eclipse.xtext.serializer.diagnostic.ISerializationDiagnostic.Acceptor;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.GenericSequencer;
import org.eclipse.xtext.serializer.sequencer.ISemanticNodeProvider.INodesForEObjectProvider;
import org.eclipse.xtext.serializer.sequencer.ISemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class HTMLGenSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private HTMLGenGrammarAccess grammarAccess;
	
	@Override
	public void createSequence(EObject context, EObject semanticObject) {
		if(semanticObject.eClass().getEPackage() == HTMLGenPackage.eINSTANCE) switch(semanticObject.eClass().getClassifierID()) {
			case HTMLGenPackage.FIELD:
				sequence_Field(context, (Field) semanticObject); 
				return; 
			case HTMLGenPackage.FORM:
				sequence_Form(context, (Form) semanticObject); 
				return; 
			case HTMLGenPackage.MODEL:
				sequence_Model(context, (Model) semanticObject); 
				return; 
			case HTMLGenPackage.MULTILINE_FIELD:
				sequence_MultilineField(context, (MultilineField) semanticObject); 
				return; 
			case HTMLGenPackage.TEXT_FIELD:
				sequence_TextField(context, (TextField) semanticObject); 
				return; 
			}
		if (errorAcceptor != null) errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Constraint:
	 *     (name=ID label=STRING)
	 */
	protected void sequence_Field(EObject context, Field semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, HTMLGenPackage.Literals.FIELD__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HTMLGenPackage.Literals.FIELD__NAME));
			if(transientValues.isValueTransient(semanticObject, HTMLGenPackage.Literals.FIELD__LABEL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HTMLGenPackage.Literals.FIELD__LABEL));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getFieldAccess().getNameIDTerminalRuleCall_0_2_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getFieldAccess().getLabelSTRINGTerminalRuleCall_0_4_0(), semanticObject.getLabel());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (name=STRING description=STRING title=STRING form+=Field form+=Field*)
	 */
	protected void sequence_Form(EObject context, Form semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (model+=Form form+=Form*)
	 */
	protected void sequence_Model(EObject context, Model semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID label=ID)
	 */
	protected void sequence_MultilineField(EObject context, MultilineField semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, HTMLGenPackage.Literals.FIELD__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HTMLGenPackage.Literals.FIELD__NAME));
			if(transientValues.isValueTransient(semanticObject, HTMLGenPackage.Literals.FIELD__LABEL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HTMLGenPackage.Literals.FIELD__LABEL));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getMultilineFieldAccess().getNameIDTerminalRuleCall_3_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getMultilineFieldAccess().getLabelIDTerminalRuleCall_5_0(), semanticObject.getLabel());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID label=STRING)
	 */
	protected void sequence_TextField(EObject context, TextField semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, HTMLGenPackage.Literals.FIELD__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HTMLGenPackage.Literals.FIELD__NAME));
			if(transientValues.isValueTransient(semanticObject, HTMLGenPackage.Literals.FIELD__LABEL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, HTMLGenPackage.Literals.FIELD__LABEL));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getTextFieldAccess().getNameIDTerminalRuleCall_0_3_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getTextFieldAccess().getLabelSTRINGTerminalRuleCall_0_5_0(), semanticObject.getLabel());
		feeder.finish();
	}
}
